Repository proplants/plantbook, pull requests merged in 2021-06, with the labels that each got.

#73 Envs from git to docker
  .github/workflows/ci-cd.yml
Labels: infrastructure

#86 add linters, fix linter remarks, aligned some variables and comments
  .golangci.yml
  database/migrations_schema/000001_roles_and_users.up.sql
  database/migrations_schema/000003_blogs_and_posts.up.sql
  database/migrations_schema/000004_user_tasks.up.sql
  go.mod
  go.sum
  internal/api/client/client_auth_test.go
  internal/api/handlers/gardens/gardens.go
  internal/api/handlers/gardens/gardens_create.go
  internal/api/handlers/gardens/gardens_delete.go
  internal/api/handlers/health/health.go
  internal/api/handlers/health/health_api_version.go
  internal/api/handlers/health/health_live.go
  internal/api/handlers/health/health_ready.go
  internal/api/handlers/refplants/plant_get_by_id.go
  internal/api/handlers/refplants/plants_get.go
  internal/api/handlers/userplants/userplant_create.go
  internal/api/handlers/userplants/userplant_get.go
  internal/api/handlers/users/users.go
  internal/api/handlers/users/users_create.go
  internal/api/handlers/users/users_login.go
  internal/api/handlers/users/users_logout.go
  internal/api/middleware/metrics.go
  internal/api/middleware/middleware.go
  internal/api/repo/pg_gardens.go
  internal/api/repo/pg_repo.go
  internal/metric/metric.go
  pkg/logging/logging.go
  pkg/token/token_jwt.go
  scripts/postman/e2e.scenario1/plantbook.scenario1.json
  utils/greenmen/main.go
  utils/greenmen/main_test.go
  utils/greenmen/model/plant_easyjson.go
  utils/greenmen/page_parser.go
  utils/randutil/randutil.go
Labels: refactoring

#94 described almost all about #93
  .github/workflows/test.yml
  assets/README_content/plantbook_k8s_alert.png
  assets/README_content/plantbook_k8s_grafana.png
  assets/README_content/plantbook_k8s_prom.png
  deploy/k8s/prepare/README.md
  deploy/k8s/prepare/manifests/ingress.yml
  deploy/k8s/prepare/manifests/sa.yaml
  deploy/k8s/prepare/manifests/servicemonitor.yml
  deploy/k8s/prepare/prometheus/prometheus.yaml
  deploy/k8s/prepare/scripts/kcfg.sh
Labels: documentation, infrastructure

#109 #108 database image
  .github/workflows/db-build.yml
  Makefile
  build/db/Dockerfile
  database/createdb/000000_create_database.sql
Labels: CI, help wanted, infrastructure

#113 Database build with version
  .github/workflows/db-build.yml
  database/createdb/000000_create_database.sql
Labels: infrastructure
