Repository proplants/plantbook, pull requests merged in 2021-05, with the labels that each got.

#23 link to the license fixed
  README.md
Labels: documentation

#66 simplified the code to load configuration
  config/config.go
  go.sum
  internal/api/restapi/configure_plantbook.go
  internal/config/cfg.go
  internal/config/cfg_test.go
Labels: enhancement

#69 61 gardens delete
  .github/workflows/ci-cd.yml
  internal/api/handlers/gardens/gardens.go
  internal/api/handlers/gardens/gardens_delete.go
  internal/api/repo/pg_gardens.go
  internal/api/restapi/configure_plantbook.go
  scripts/postman/plantbook.postman_collection.json
Labels: help wanted
